### ISSUE TITLE
Set repository as public archive

### ISSUE THREAD

**Issue by pedropaulofb** [nemo-ufes/ontouml-lightweight-editor#9]
This repository's last update was 5 years ago and, as far as I know, there are no initiatives to continue the OLED development.

Could you please set it as "public archive", clarifying to users that it was discontinued?

Before doing that, I endorse the recommendation in issue #5. It would be important to provide users with information about the most recent tools being developed, especially the [Visual Paradigm OntoUML Plugin](https://github.com/OntoUML/ontouml-vp-plugin).

**Comment by vitorsouza** [comment]
Thanks for the suggestion. The repository has been archived.
